FROM golang:1.22 as build
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o input-service ./cmd/main.go

FROM scratch
WORKDIR /app
COPY --from=build /app/.env .
COPY --from=build /app/input-service .
ENTRYPOINT ["./input-service"]